@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}/api
@contentType = application/json

POST http://{{host}}/webhooks/ HTTP/1.1
content-type: {{contentType}}

{
    "url": "https://webhook.site/765fdfd3-14a8-4ccf-b062-b82025f70ce3",
    "name": "Testing Webhook",
    "merchantId": "ljalksdj8798asdlkjl",
    "key": "klajsdkljalksdjlkaioausoid"
}

###

GET http://{{host}}/webhooks/ HTTP/1.1 

###

GET http://{{host}}/webhooks/611ce59b7b9f4c00d5efa57e HTTP/1.1 